# -*- coding: utf-8 -*-
from PyQt5.QtCore import QDateTime

# Form implementation generated from reading ui file 'add_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import design.res
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(400, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(400, 550))
        Dialog.setMaximumSize(QtCore.QSize(400, 550))
        Dialog.setSizeIncrement(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/src/image/icon_1.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(179, 200, 207);")
        Dialog.setModal(False)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(20, 20, 361, 451))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.position_comboBox = QtWidgets.QComboBox(self.frame)
        self.position_comboBox.setGeometry(QtCore.QRect(110, 250, 241, 35))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(14)
        self.position_comboBox.setFont(font)
        self.position_comboBox.setStyleSheet("QComboBox {\n"
"                background-color: rgb(255, 255, 255);\n"
"                border: 2px solid  rgb(0, 31, 63);\n"
"                border-radius: 8px;\n"
"                padding: 5px;\n"
"                font-size: 14pt;\n"
"                color: rgb(50, 50, 50);\n"
"            }\n"
"            QComboBox::drop-down {\n"
"                background-color: rgb(0, 31, 63);\n"
"                border: none;\n"
"                width: 25px;\n"
"            }\n"
"            QComboBox::down-arrow {\n"
"                image: url(:/img/src/image/chevron_down.png); \n"
"                width: 12px;\n"
"                height: 12px;\n"
"            }")
        self.position_comboBox.setObjectName("position_comboBox")
        self.hire_date_dateEdit = QtWidgets.QDateEdit(self.frame)
        self.hire_date_dateEdit.setGeometry(QtCore.QRect(111, 300, 241, 35))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(14)
        self.hire_date_dateEdit.setFont(font)
        self.hire_date_dateEdit.setStyleSheet("QDateEdit {\n"
"                background-color: rgb(255, 255, 255);\n"
"                border: 2px solid  rgb(0, 31, 63);\n"
"                border-radius: 8px;\n"
"                padding: 5px;\n"
"                font-size: 14pt;\n"
"                color: rgb(50, 50, 50);\n"
"            }\n"
"QDateEdit::drop-down {\n"
"                background-color: rgb(0, 31, 63);\n"
"                border: none;\n"
"                width: 25px;\n"
"            }\n"
"            QDateEdit::down-arrow {\n"
"                image: url(:/img/src/image/chevron_down.png); \n"
"                width: 12px;\n"
"                height: 12px;\n"
"            }\n"
"            QDateEdit QCalendarWidget {\n"
"                background-color: rgb(240, 240, 240);\n"
"                border: 1px solid rgb(200, 200, 200);\n"
"                font-size: 12pt;\n"
"                color: rgb(0, 0, 0);\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"            QDateEdit QCalendarWidget QToolButton {\n"
"                color: rgb(0, 31, 63);\n"
"                font-size: 12pt;\n"
"                border: none;\n"
"                margin: 5px;\n"
"                padding: 5px;\n"
"                border-radius: 5px;\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"            QDateEdit QCalendarWidget QToolButton:hover {\n"
"                background-color: rgb(58, 109, 140);\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"            QDateEdit QCalendarWidget QTableView {\n"
"                background-color: white;\n"
"                color: black;\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"QDateEdit QCalendarWidget QTableView:selected {\n"
"                background-color: rgb(0, 122, 204);\n"
"                color: white;\n"
"                font: 25 16pt \"Caros Light\";\n"
" }\n"
"QDateEdit QCalendarWidget QToolButton#qt_calendar_prevmonth  {\n"
"    qproperty-icon: none;\n"
"    image: url(:/img/src/image/Left.png);\n"
"}\n"
"\n"
"QDateEdit QCalendarWidget QToolButton#qt_calendar_nextmonth {\n"
"    qproperty-icon: none;\n"
"    image: url(:/img/src/image/Right.png); \n"
"}\n"
"")
        self.hire_date_dateEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.hire_date_dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1945, 9, 14), QtCore.QTime(0, 0, 0)))
        self.hire_date_dateEdit.setCalendarPopup(True)
        self.hire_date_dateEdit.setObjectName("hire_date_dateEdit")
        self.hire_date_dateEdit.setDateTime(QDateTime.currentDateTime())
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 10, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:  rgb(0, 31, 63);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(1, 60, 91, 19))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:  rgb(0, 31, 63);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(1, 110, 88, 19))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:  rgb(0, 31, 63);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(1, 210, 103, 19))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:  rgb(0, 31, 63);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(1, 260, 78, 19))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:  rgb(0, 31, 63);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(1, 310, 81, 19))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:  rgb(0, 31, 63);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(1, 340, 96, 51))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAcceptDrops(False)
        self.label_7.setStyleSheet("color:  rgb(0, 31, 63);")
        self.label_7.setScaledContents(False)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(1, 410, 91, 19))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:  rgb(0, 31, 63);")
        self.label_8.setObjectName("label_8")
        self.birth_date_dateEdit = QtWidgets.QDateEdit(self.frame)
        self.birth_date_dateEdit.setGeometry(QtCore.QRect(110, 400, 241, 35))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(14)
        self.birth_date_dateEdit.setFont(font)
        self.birth_date_dateEdit.setStyleSheet("QDateEdit {\n"
"                background-color: rgb(255, 255, 255);\n"
"                border: 2px solid  rgb(0, 31, 63);\n"
"                border-radius: 8px;\n"
"                padding: 5px;\n"
"                font-size: 14pt;\n"
"                color: rgb(50, 50, 50);\n"
"            }\n"
"QDateEdit::drop-down {\n"
"                background-color: rgb(0, 31, 63);\n"
"                border: none;\n"
"                width: 25px;\n"
"            }\n"
"            QDateEdit::down-arrow {\n"
"                image: url(:/img/src/image/chevron_down.png); \n"
"                width: 12px;\n"
"                height: 12px;\n"
"            }\n"
"            QDateEdit QCalendarWidget {\n"
"                background-color: rgb(240, 240, 240);\n"
"                border: 1px solid rgb(200, 200, 200);\n"
"                font-size: 12pt;\n"
"                color: rgb(0, 0, 0);\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"            QDateEdit QCalendarWidget QToolButton {\n"
"                color: rgb(0, 31, 63);\n"
"                font-size: 12pt;\n"
"                border: none;\n"
"                margin: 5px;\n"
"                padding: 5px;\n"
"                border-radius: 5px;\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"            QDateEdit QCalendarWidget QToolButton:hover {\n"
"                background-color: rgb(58, 109, 140);\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"            QDateEdit QCalendarWidget QTableView {\n"
"                background-color: white;\n"
"                color: black;\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"QDateEdit QCalendarWidget QTableView:selected {\n"
"                background-color: rgb(0, 122, 204);\n"
"                color: white;\n"
"                font: 25 16pt \"Caros Light\";\n"
" }\n"
"QDateEdit QCalendarWidget QToolButton#qt_calendar_prevmonth  {\n"
"    qproperty-icon: none;\n"
"    image: url(:/img/src/image/Left.png);\n"
"}\n"
"\n"
"QDateEdit QCalendarWidget QToolButton#qt_calendar_nextmonth {\n"
"    qproperty-icon: none;\n"
"    image: url(:/img/src/image/Right.png); \n"
"}\n"
"")

        self.birth_date_dateEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.birth_date_dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1945, 9, 14), QtCore.QTime(0, 0, 0)))
        self.birth_date_dateEdit.setCalendarPopup(True)
        self.birth_date_dateEdit.setObjectName("birth_date_dateEdit")
        self.experience_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.experience_lineEdit.setGeometry(QtCore.QRect(110, 350, 241, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.experience_lineEdit.setFont(font)
        self.experience_lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid  rgb(0, 31, 63);\n"
"    border-radius: 8px; \n"
"    padding: 5px; \n"
"    font-size: 10pt;\n"
"}")
        self.experience_lineEdit.setMaxLength(100)
        self.experience_lineEdit.setObjectName("experience_lineEdit")
        self.full_name_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.full_name_lineEdit.setGeometry(QtCore.QRect(110, 100, 241, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.full_name_lineEdit.setFont(font)
        self.full_name_lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid  rgb(0, 31, 63);\n"
"    border-radius: 8px; \n"
"    padding: 5px; \n"
"    font-size: 10pt;\n"
"}")
        self.full_name_lineEdit.setText("")
        self.full_name_lineEdit.setMaxLength(100)
        self.full_name_lineEdit.setPlaceholderText("")
        self.full_name_lineEdit.setObjectName("full_name_lineEdit")
        self.password_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.password_lineEdit.setGeometry(QtCore.QRect(110, 50, 241, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid  rgb(0, 31, 63);\n"
"    border-radius: 8px; \n"
"    padding: 5px; \n"
"    font-size: 10pt;\n"
"}")
        self.password_lineEdit.setMaxLength(100)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.login_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.login_lineEdit.setGeometry(QtCore.QRect(110, 0, 241, 35))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(10)
        self.login_lineEdit.setFont(font)
        self.login_lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid  rgb(0, 31, 63);\n"
"    border-radius: 8px; \n"
"    padding: 5px; \n"
"    font-size: 10pt;\n"
"}")
        self.login_lineEdit.setMaxLength(100)
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.department_comboBox = QtWidgets.QComboBox(self.frame)
        self.department_comboBox.setGeometry(QtCore.QRect(110, 200, 241, 35))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(14)
        self.department_comboBox.setFont(font)
        self.department_comboBox.setStyleSheet("QComboBox {\n"
"                background-color: rgb(255, 255, 255);\n"
"                border: 2px solid  rgb(0, 31, 63);\n"
"                border-radius: 8px;\n"
"                padding: 5px;\n"
"                font-size: 14pt;\n"
"                color: rgb(50, 50, 50);\n"
"            }\n"
"            QComboBox::drop-down {\n"
"                background-color: rgb(0, 31, 63);\n"
"                border: none;\n"
"                width: 25px;\n"
"            }\n"
"            QComboBox::down-arrow {\n"
"                image: url(:/img/src/image/chevron_down.png); \n"
"                width: 12px;\n"
"                height: 12px;\n"
"            }")
        self.department_comboBox.setCurrentText("")
        self.department_comboBox.setObjectName("department_comboBox")
        self.sex_comboBox = QtWidgets.QComboBox(self.frame)
        self.sex_comboBox.setGeometry(QtCore.QRect(110, 150, 241, 35))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(14)
        self.sex_comboBox.setFont(font)
        self.sex_comboBox.setStyleSheet("QComboBox {\n"
"                background-color: rgb(255, 255, 255);\n"
"                border: 2px solid  rgb(0, 31, 63);\n"
"                border-radius: 8px;\n"
"                padding: 5px;\n"
"                font-size: 14pt;\n"
"                color: rgb(50, 50, 50);\n"
"            }\n"
"            QComboBox::drop-down {\n"
"                background-color: rgb(0, 31, 63);\n"
"                border: none;\n"
"                width: 25px;\n"
"            }\n"
"            QComboBox::down-arrow {\n"
"                image: url(:/img/src/image/chevron_down.png); \n"
"                width: 12px;\n"
"                height: 12px;\n"
"            }")
        self.sex_comboBox.setEditable(False)
        self.sex_comboBox.setCurrentText("")
        self.sex_comboBox.setObjectName("sex_comboBox")
        self.sex_comboBox.addItems(["Male", "Female"])
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(0, 160, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:  rgb(0, 31, 63);")
        self.label_9.setObjectName("label_9")
        self.save_pushButton = QtWidgets.QPushButton(Dialog)
        self.save_pushButton.setGeometry(QtCore.QRect(50, 480, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.save_pushButton.setFont(font)
        self.save_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 31, 63);\n"
"border-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(58, 109, 140);\n"
"}")
        self.save_pushButton.setObjectName("save_pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Worker"))
        self.label.setText(_translate("Dialog", "LOGIN"))
        self.label_2.setText(_translate("Dialog", "PASSWORD"))
        self.label_3.setText(_translate("Dialog", "FULL NAME"))
        self.label_4.setText(_translate("Dialog", "DEPARTMENT"))
        self.label_5.setText(_translate("Dialog", "POSITION"))
        self.label_6.setText(_translate("Dialog", "HIRE DATE"))
        self.label_7.setText(_translate("Dialog", "PREVIOUS EXPERIENCE"))
        self.label_8.setText(_translate("Dialog", "BIRTH DATE"))
        self.label_9.setText(_translate("Dialog", "SEX"))
        self.save_pushButton.setText(_translate("Dialog", "SAVE"))

