# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import design.res
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        Form.setMinimumSize(QtCore.QSize(1000, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/src/image/icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.welcome_page = QtWidgets.QWidget()
        self.welcome_page.setObjectName("welcome_page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.welcome_page)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_7 = QtWidgets.QFrame(self.welcome_page)
        self.frame_7.setStyleSheet("image: url(:/img/src/image/office-amico.png);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_6.addWidget(self.frame_7, 1, 0, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.welcome_page)
        self.label_2.setMinimumSize(QtCore.QSize(0, 110))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 110))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 31, 63);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.welcome_page)
        self.frame_6.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border-radius:20px;\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 31, 63);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 31, 63);")
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 31, 63);")
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 31, 63);")
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 3, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_7.addWidget(self.frame_8, 1, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_7.addWidget(self.frame_9, 1, 2, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 75))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_7.addWidget(self.frame_10, 4, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame_6, 0, 1, 3, 1)
        self.stackedWidget.addWidget(self.welcome_page)
        self.manage_employees_page = QtWidgets.QWidget()
        self.manage_employees_page.setObjectName("manage_employees_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.manage_employees_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.manage_employees_page)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.edit_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.edit_pushButton.setMinimumSize(QtCore.QSize(0, 75))
        self.edit_pushButton.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(16)
        self.edit_pushButton.setFont(font)
        self.edit_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 31, 63);\n"
"border-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(58, 109, 140);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/src/image/edit_row.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.edit_pushButton.setIcon(icon1)
        self.edit_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.edit_pushButton.setObjectName("edit_pushButton")
        self.gridLayout_3.addWidget(self.edit_pushButton, 3, 0, 1, 1)
        self.delete_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.delete_pushButton.setMinimumSize(QtCore.QSize(0, 75))
        self.delete_pushButton.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(16)
        self.delete_pushButton.setFont(font)
        self.delete_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 31, 63);\n"
"border-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(58, 109, 140);\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/src/image/denied.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.delete_pushButton.setIcon(icon2)
        self.delete_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.gridLayout_3.addWidget(self.delete_pushButton, 4, 0, 1, 1)
        self.add_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.add_pushButton.setMinimumSize(QtCore.QSize(0, 75))
        self.add_pushButton.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.add_pushButton.setFont(font)
        self.add_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 31, 63);\n"
"border-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(58, 109, 140);\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/src/image/add_user.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.add_pushButton.setIcon(icon3)
        self.add_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.add_pushButton.setObjectName("add_pushButton")
        self.gridLayout_3.addWidget(self.add_pushButton, 1, 0, 1, 1)
        self.view_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.view_pushButton.setMinimumSize(QtCore.QSize(0, 75))
        self.view_pushButton.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(16)
        self.view_pushButton.setFont(font)
        self.view_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 31, 63);\n"
"border-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(58, 109, 140);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/src/image/analyze.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.view_pushButton.setIcon(icon4)
        self.view_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.view_pushButton.setObjectName("view_pushButton")
        self.gridLayout_3.addWidget(self.view_pushButton, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 1, 1, 1, 1)
        self.worker_tableView = QtWidgets.QTableView(self.manage_employees_page)
        self.worker_tableView.setStyleSheet("QHeaderView::section {\n"
"    background-color: rgb(0, 31, 63);\n"
"    color: white;\n"
"    font-size: 14pt;\n"
"    font-weight: bold;\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    padding: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: rgb(230, 230, 230);\n"
"    width: 12px;\n"
"    margin: 0px 3px 0px 3px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(150, 150, 150);\n"
"    min-height: 20px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background: rgb(230, 230, 230);\n"
"    height: 12px;\n"
"    margin: 3px 0px 3px 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(150, 150, 150);\n"
"    min-width: 20px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"}")
        self.worker_tableView.setSortingEnabled(True)
        self.worker_tableView.setObjectName("worker_tableView")
        self.gridLayout_2.addWidget(self.worker_tableView, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.manage_employees_page)
        self.calculate_salary_page = QtWidgets.QWidget()
        self.calculate_salary_page.setObjectName("calculate_salary_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.calculate_salary_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.worker_salary_tableWidget = QtWidgets.QTableWidget(self.calculate_salary_page)
        self.worker_salary_tableWidget.setObjectName("worker_salary_tableWidget")
        self.worker_salary_tableWidget.setColumnCount(0)
        self.worker_salary_tableWidget.setRowCount(0)
        self.gridLayout_4.addWidget(self.worker_salary_tableWidget, 1, 1, 1, 1)
        self.worker_leaves_tableView = QtWidgets.QTableView(self.calculate_salary_page)
        self.worker_leaves_tableView.setObjectName("worker_leaves_tableView")
        self.gridLayout_4.addWidget(self.worker_leaves_tableView, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.calculate_salary_page)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4.addWidget(self.frame_3, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.calculate_salary_page)
        self.generate_report_page = QtWidgets.QWidget()
        self.generate_report_page.setObjectName("generate_report_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.generate_report_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.generate_report_page)
        self.frame_4.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.generate_report_page)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5.addWidget(self.frame_5, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.generate_report_page)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget.setStyleSheet("background-color: rgb(179, 200, 207);\n"
"border-radius: 15px;")
        self.widget.setObjectName("widget")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(40, 30, 121, 121))
        self.frame.setStyleSheet("image: url(:/img/src/image/icon.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 160, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 31, 63);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.calculate_salary_pushButton = QtWidgets.QPushButton(self.widget)
        self.calculate_salary_pushButton.setGeometry(QtCore.QRect(0, 300, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.calculate_salary_pushButton.setFont(font)
        self.calculate_salary_pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 0px;\n"
"color: rgb(0, 31, 63);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius: 0px;\n"
"background-color: rgb(58, 109, 140);\n"
"color: rgb(0, 31, 63);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/src/image/salary.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.calculate_salary_pushButton.setIcon(icon5)
        self.calculate_salary_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.calculate_salary_pushButton.setObjectName("calculate_salary_pushButton")
        self.generate_report_pushButton = QtWidgets.QPushButton(self.widget)
        self.generate_report_pushButton.setGeometry(QtCore.QRect(0, 370, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.generate_report_pushButton.setFont(font)
        self.generate_report_pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 0px;\n"
"color: rgb(0, 31, 63);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius: 0px;\n"
"background-color: rgb(58, 109, 140);\n"
"color: rgb(0, 31, 63);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/src/image/document.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.generate_report_pushButton.setIcon(icon6)
        self.generate_report_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.generate_report_pushButton.setObjectName("generate_report_pushButton")
        self.manage_employees_pushButton = QtWidgets.QPushButton(self.widget)
        self.manage_employees_pushButton.setGeometry(QtCore.QRect(0, 230, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.manage_employees_pushButton.setFont(font)
        self.manage_employees_pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 0px;\n"
"color: rgb(0, 31, 63);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius: 0px;\n"
"background-color: rgb(58, 109, 140);\n"
"color: rgb(0, 31, 63);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/src/image/employee.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.manage_employees_pushButton.setIcon(icon7)
        self.manage_employees_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.manage_employees_pushButton.setObjectName("manage_employees_pushButton")
        self.exit_pushButton = QtWidgets.QPushButton(self.widget)
        self.exit_pushButton.setGeometry(QtCore.QRect(0, 450, 201, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_pushButton.sizePolicy().hasHeightForWidth())
        self.exit_pushButton.setSizePolicy(sizePolicy)
        self.exit_pushButton.setMinimumSize(QtCore.QSize(201, 41))
        self.exit_pushButton.setMaximumSize(QtCore.QSize(201, 41))
        self.exit_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/img/src/image/exit.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/img/src/image/exit_hover.png);\n"
"}\n"
"")
        self.exit_pushButton.setText("")
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.columnView = QtWidgets.QColumnView(self.widget)
        self.columnView.setGeometry(QtCore.QRect(200, 320, 256, 192))
        self.columnView.setObjectName("columnView")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        # self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "StaffBase"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">Welcome to </span></p><p align=\"center\"><span style=\" font-size:28pt;\">the admin panel!</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "CHOOSE AN ACTION:"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">2. Calculate Salaries:</span> Process salaries with adjustments for bonuses and deductions.</p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">1. Manage Employees:</span> Add, edit or delete employee records.</p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">3. Generate Reports:</span> Create salary, attendance and department performance reports.</p></body></html>"))
        self.edit_pushButton.setText(_translate("Form", "EDIT"))
        self.delete_pushButton.setText(_translate("Form", "DELETE"))
        self.add_pushButton.setText(_translate("Form", "ADD"))
        self.view_pushButton.setText(_translate("Form", "VIEW"))
        self.label.setText(_translate("Form", "StaffBase"))
        self.calculate_salary_pushButton.setText(_translate("Form", "CALCULATE SALARY"))
        self.generate_report_pushButton.setText(_translate("Form", "GENERATE REPORT"))
        self.manage_employees_pushButton.setText(_translate("Form", "MANAGE EMPLOYEES"))
