# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth_pages.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import design.res_auth
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/src/image/icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("/*background-color: rgb(102, 174, 235, 0.7);*/\n"
"/*background-color: rgb(179, 200, 207);*/\n"
"background-color: rgb(241, 240, 232);")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.label = QtWidgets.QLabel(self.main_page)
        self.label.setGeometry(QtCore.QRect(100, 150, 601, 64))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.main_page)
        self.label_2.setGeometry(QtCore.QRect(200, 250, 401, 39))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.admin_pushButton = QtWidgets.QPushButton(self.main_page)
        self.admin_pushButton.setGeometry(QtCore.QRect(120, 330, 241, 75))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(24)
        self.admin_pushButton.setFont(font)
        self.admin_pushButton.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.admin_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(39, 39, 39);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/src/image/admin.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.admin_pushButton.setIcon(icon1)
        self.admin_pushButton.setIconSize(QtCore.QSize(32, 32))
        self.admin_pushButton.setAutoRepeatInterval(100)
        self.admin_pushButton.setObjectName("admin_pushButton")
        self.user_pushButton = QtWidgets.QPushButton(self.main_page)
        self.user_pushButton.setGeometry(QtCore.QRect(450, 330, 241, 75))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(24)
        self.user_pushButton.setFont(font)
        self.user_pushButton.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.user_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(39, 39, 39);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/src/image/user.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.user_pushButton.setIcon(icon2)
        self.user_pushButton.setIconSize(QtCore.QSize(32, 32))
        self.user_pushButton.setObjectName("user_pushButton")
        self.line = QtWidgets.QFrame(self.main_page)
        self.line.setGeometry(QtCore.QRect(180, 230, 441, 1))
        self.line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.stackedWidget.addWidget(self.main_page)
        self.admin_auth_page = QtWidgets.QWidget()
        self.admin_auth_page.setObjectName("admin_auth_page")
        self.frame = QtWidgets.QFrame(self.admin_auth_page)
        self.frame.setGeometry(QtCore.QRect(200, 100, 400, 400))
        self.frame.setStyleSheet("background-color:  rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 60, 401, 46))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.admin_password_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.admin_password_lineEdit.setGeometry(QtCore.QRect(50, 170, 300, 50))
        self.admin_password_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); \n"
"    border-radius: 20px; \n"
"    padding: 5px; \n"
"    font-size: 14pt;\n"
"}")
        self.admin_password_lineEdit.setMaxLength(20)
        self.admin_password_lineEdit.setObjectName("admin_password_lineEdit")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 130, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.login_admin_pushButton = QtWidgets.QPushButton(self.frame)
        self.login_admin_pushButton.setGeometry(QtCore.QRect(50, 280, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.login_admin_pushButton.setFont(font)
        self.login_admin_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30px;\n"
"padding: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(39, 39, 39);\n"
"}")
        self.login_admin_pushButton.setObjectName("login_admin_pushButton")
        self.forgot_admin_pushButton = QtWidgets.QPushButton(self.frame)
        self.forgot_admin_pushButton.setGeometry(QtCore.QRect(150, 220, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.forgot_admin_pushButton.setFont(font)
        self.forgot_admin_pushButton.setStyleSheet("QPushButton:hover {\n"
"color: rgb(0, 0, 255);\n"
"}")
        self.forgot_admin_pushButton.setObjectName("forgot_admin_pushButton")
        self.admin_back_pushButton = QtWidgets.QPushButton(self.admin_auth_page)
        self.admin_back_pushButton.setGeometry(QtCore.QRect(10, 10, 75, 51))
        self.admin_back_pushButton.setStyleSheet("QPushButton {\n"
"                background-color: rgba(255, 255, 255, 0);\n"
"                image: url(:/img/src/image/arrow_back.png);\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgba(255, 255, 255, 0);\n"
"                image: url(:/img/src/image/arrow_back_hover.png);\n"
"            }")
        self.admin_back_pushButton.setText("")
        self.admin_back_pushButton.setObjectName("admin_back_pushButton")
        self.stackedWidget.addWidget(self.admin_auth_page)
        self.user_auth_page = QtWidgets.QWidget()
        self.user_auth_page.setObjectName("user_auth_page")
        self.frame_2 = QtWidgets.QFrame(self.user_auth_page)
        self.frame_2.setGeometry(QtCore.QRect(200, 49, 400, 501))
        self.frame_2.setStyleSheet("background-color:  rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(0, 75, 401, 46))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.admin_password_lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.admin_password_lineEdit_2.setGeometry(QtCore.QRect(50, 285, 300, 50))
        self.admin_password_lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); \n"
"    border-radius: 20px; \n"
"    padding: 5px; \n"
"    font-size: 14pt;\n"
"}")
        self.admin_password_lineEdit_2.setMaxLength(20)
        self.admin_password_lineEdit_2.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.admin_password_lineEdit_2.setObjectName("admin_password_lineEdit_2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(50, 245, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.login_admin_pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.login_admin_pushButton_2.setGeometry(QtCore.QRect(50, 400, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.login_admin_pushButton_2.setFont(font)
        self.login_admin_pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30px;\n"
"padding: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(39, 39, 39);\n"
"}")
        self.login_admin_pushButton_2.setObjectName("login_admin_pushButton_2")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(168, 30, 47, 41))
        self.label_7.setStyleSheet("image: url(:/img/src/image/staff.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.admin_password_lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.admin_password_lineEdit_3.setGeometry(QtCore.QRect(50, 180, 300, 50))
        self.admin_password_lineEdit_3.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); \n"
"    border-radius: 20px; \n"
"    padding: 5px; \n"
"    font-size: 14pt;\n"
"}\n"
"")
        self.admin_password_lineEdit_3.setMaxLength(50)
        self.admin_password_lineEdit_3.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.admin_password_lineEdit_3.setObjectName("admin_password_lineEdit_3")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(50, 140, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.forgot_user_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.forgot_user_pushButton.setGeometry(QtCore.QRect(150, 340, 191, 30))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.forgot_user_pushButton.setFont(font)
        self.forgot_user_pushButton.setStyleSheet("QPushButton:hover {\n"
"color: rgb(0, 0, 255);\n"
"}")
        self.forgot_user_pushButton.setObjectName("forgot_user_pushBotton")
        self.user_back_pushButton = QtWidgets.QPushButton(self.user_auth_page)
        self.user_back_pushButton.setGeometry(QtCore.QRect(10, 10, 75, 51))
        self.user_back_pushButton.setStyleSheet("QPushButton {\n"
"                background-color: rgba(255, 255, 255, 0);\n"
"                image: url(:/img/src/image/arrow_back.png);\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgba(255, 255, 255, 0);\n"
"                image: url(:/img/src/image/arrow_back_hover.png);\n"
"            }\n"
"")
        self.user_back_pushButton.setText("")
        self.user_back_pushButton.setObjectName("user_back_pushButton")
        self.stackedWidget.addWidget(self.user_auth_page)
        self.code_page = QtWidgets.QWidget()
        self.code_page.setObjectName("code_page")
        self.label_9 = QtWidgets.QLabel(self.code_page)
        self.label_9.setGeometry(QtCore.QRect(200, 100, 401, 81))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.email_textEdit = QtWidgets.QTextEdit(self.code_page)
        self.email_textEdit.setGeometry(QtCore.QRect(200, 175, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.email_textEdit.setFont(font)
        self.email_textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.email_textEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.email_textEdit.setLineWidth(0)
        self.email_textEdit.setTabChangesFocus(False)
        self.email_textEdit.setReadOnly(True)
        self.email_textEdit.setAcceptRichText(True)
        self.email_textEdit.setObjectName("email_textEdit")
        self.first_n_lineEdit = QtWidgets.QLineEdit(self.code_page)
        self.first_n_lineEdit.setGeometry(QtCore.QRect(170, 300, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.first_n_lineEdit.setFont(font)
        self.first_n_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); \n"
"    border-radius: 20px; \n"
"    padding: 5px; \n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.first_n_lineEdit.setMaxLength(1)
        self.first_n_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.first_n_lineEdit.setObjectName("first_n_lineEdit")
        self.second_n_lineEdit = QtWidgets.QLineEdit(self.code_page)
        self.second_n_lineEdit.setGeometry(QtCore.QRect(250, 300, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.second_n_lineEdit.setFont(font)
        self.second_n_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); \n"
"    border-radius: 20px; \n"
"    padding: 5px; \n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.second_n_lineEdit.setMaxLength(1)
        self.second_n_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.second_n_lineEdit.setObjectName("second_n_lineEdit")
        self.third_n_lineEdit = QtWidgets.QLineEdit(self.code_page)
        self.third_n_lineEdit.setGeometry(QtCore.QRect(330, 300, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.third_n_lineEdit.setFont(font)
        self.third_n_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); \n"
"    border-radius: 20px; \n"
"    padding: 5px; \n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.third_n_lineEdit.setMaxLength(1)
        self.third_n_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.third_n_lineEdit.setObjectName("third_n_lineEdit")
        self.forth_n_lineEdit = QtWidgets.QLineEdit(self.code_page)
        self.forth_n_lineEdit.setGeometry(QtCore.QRect(410, 300, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.forth_n_lineEdit.setFont(font)
        self.forth_n_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); \n"
"    border-radius: 20px; \n"
"    padding: 5px; \n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.forth_n_lineEdit.setMaxLength(1)
        self.forth_n_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.forth_n_lineEdit.setObjectName("forth_n_lineEdit")
        self.fifth_n_lineEdit = QtWidgets.QLineEdit(self.code_page)
        self.fifth_n_lineEdit.setGeometry(QtCore.QRect(490, 300, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fifth_n_lineEdit.setFont(font)
        self.fifth_n_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); \n"
"    border-radius: 20px; \n"
"    padding: 5px; \n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.fifth_n_lineEdit.setMaxLength(1)
        self.fifth_n_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.fifth_n_lineEdit.setObjectName("fifth_n_lineEdit")
        self.sixth_n_lineEdit = QtWidgets.QLineEdit(self.code_page)
        self.sixth_n_lineEdit.setGeometry(QtCore.QRect(570, 300, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sixth_n_lineEdit.setFont(font)
        self.sixth_n_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); \n"
"    border-radius: 20px; \n"
"    padding: 5px; \n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.sixth_n_lineEdit.setMaxLength(1)
        self.sixth_n_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.sixth_n_lineEdit.setObjectName("sixth_n_lineEdit")
        self.code_continue_pushButton = QtWidgets.QPushButton(self.code_page)
        self.code_continue_pushButton.setGeometry(QtCore.QRect(300, 427, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.code_continue_pushButton.setFont(font)
        self.code_continue_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30px;\n"
"padding: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(39, 39, 39);\n"
"}")
        self.code_continue_pushButton.setObjectName("code_continue_pushButton")
        self.label_10 = QtWidgets.QLabel(self.code_page)
        self.label_10.setGeometry(QtCore.QRect(200, 255, 401, 30))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.code_page)
        self.recovery_page = QtWidgets.QWidget()
        self.recovery_page.setObjectName("recovery_page")
        self.frame_3 = QtWidgets.QFrame(self.recovery_page)
        self.frame_3.setGeometry(QtCore.QRect(200, 48, 401, 501))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.confirm_new_password_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.confirm_new_password_lineEdit.setGeometry(QtCore.QRect(50, 276, 300, 50))
        self.confirm_new_password_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); \n"
"    border-radius: 20px; \n"
"    padding: 5px; \n"
"    font-size: 14pt;\n"
"}\n"
"")
        self.confirm_new_password_lineEdit.setMaxLength(20)
        self.confirm_new_password_lineEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.confirm_new_password_lineEdit.setObjectName("confirm_new_password_lineEdit")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(50, 240, 201, 25))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(50, 144, 176, 25))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(50, 50, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.reset_password_pushButton = QtWidgets.QPushButton(self.frame_3)
        self.reset_password_pushButton.setGeometry(QtCore.QRect(50, 384, 301, 73))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.reset_password_pushButton.setFont(font)
        self.reset_password_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30px;\n"
"padding: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(39, 39, 39);\n"
"}")
        self.reset_password_pushButton.setObjectName("reset_password_pushButton")
        self.new_password_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.new_password_lineEdit.setGeometry(QtCore.QRect(50, 175, 300, 50))
        self.new_password_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); \n"
"    border-radius: 20px; \n"
"    padding: 5px; \n"
"    font-size: 14pt;\n"
"}\n"
"")
        self.new_password_lineEdit.setMaxLength(20)
        self.new_password_lineEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.new_password_lineEdit.setObjectName("new_password_lineEdit")
        self.stackedWidget.addWidget(self.recovery_page)
        self.user_login_page = QtWidgets.QWidget()
        self.user_login_page.setObjectName("user_login_page")
        self.login_for_pass_lineEdit = QtWidgets.QLineEdit(self.user_login_page)
        self.login_for_pass_lineEdit.setGeometry(QtCore.QRect(200, 250, 401, 51))
        self.login_for_pass_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); \n"
"    border-radius: 20px; \n"
"    padding: 5px; \n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 14pt;\n"
"}")
        self.login_for_pass_lineEdit.setMaxLength(50)
        self.login_for_pass_lineEdit.setObjectName("login_for_pass_lineEdit")
        self.label_14 = QtWidgets.QLabel(self.user_login_page)
        self.label_14.setGeometry(QtCore.QRect(200, 175, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.login_back_pushButton = QtWidgets.QPushButton(self.user_login_page)
        self.login_back_pushButton.setGeometry(QtCore.QRect(10, 10, 75, 51))
        self.login_back_pushButton.setStyleSheet("QPushButton {\n"
"                background-color: rgba(255, 255, 255, 0);\n"
"                image: url(:/img/src/image/arrow_back.png);\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgba(255, 255, 255, 0);\n"
"                image: url(:/img/src/image/arrow_back_hover.png);\n"
"            }\n"
"")
        self.login_back_pushButton.setText("")
        self.login_back_pushButton.setObjectName("login_back_pushButton")
        self.continue_rec_pushButton = QtWidgets.QPushButton(self.user_login_page)
        self.continue_rec_pushButton.setGeometry(QtCore.QRect(234, 340, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.continue_rec_pushButton.setFont(font)
        self.continue_rec_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30px;\n"
"padding: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(39, 39, 39);\n"
"}")
        self.continue_rec_pushButton.setObjectName("continue_rec_pushButton")
        self.stackedWidget.addWidget(self.user_login_page)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "StaffBase"))
        self.label.setText(_translate("MainWindow", "Welcome to StaffBase"))
        self.label_2.setText(_translate("MainWindow", "Please select your role"))
        self.admin_pushButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.admin_pushButton.setText(_translate("MainWindow", "Admin"))
        self.user_pushButton.setText(_translate("MainWindow", "Employee"))
        self.label_3.setText(_translate("MainWindow", "Login as administrator"))
        self.label_4.setText(_translate("MainWindow", "Enter password"))
        self.login_admin_pushButton.setText(_translate("MainWindow", "LOGIN"))
        self.forgot_admin_pushButton.setText(_translate("MainWindow", "Forgot your password?"))
        self.label_5.setText(_translate("MainWindow", "Login to your account"))
        self.label_6.setText(_translate("MainWindow", "Enter your password"))
        self.login_admin_pushButton_2.setText(_translate("MainWindow", "LOGIN"))
        self.label_8.setText(_translate("MainWindow", "Enter your username"))
        self.forgot_user_pushButton.setText(_translate("MainWindow", "Forgot your password?"))
        self.label_9.setText(_translate("MainWindow", "A code has been sent to"))
        self.email_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Caros Black\'; font-size:24pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.code_continue_pushButton.setText(_translate("MainWindow", "CONTINUE"))
        self.label_10.setText(_translate("MainWindow", "Enter the received code"))
        self.label_11.setText(_translate("MainWindow", "Confirm new password"))
        self.label_12.setText(_translate("MainWindow", "Enter new password"))
        self.label_13.setText(_translate("MainWindow", "Change password"))
        self.reset_password_pushButton.setText(_translate("MainWindow", "RESET PASSWORD"))
        self.label_14.setText(_translate("MainWindow", "Enter your login"))
        self.continue_rec_pushButton.setText(_translate("MainWindow", "CONTINUE"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
