# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_personal_info_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import design.res
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/src/image/edit_icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(179, 200, 207);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.maritual_status_comboBox = QtWidgets.QComboBox(self.frame)
        self.maritual_status_comboBox.setGeometry(QtCore.QRect(120, 70, 241, 35))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(14)
        self.maritual_status_comboBox.setFont(font)
        self.maritual_status_comboBox.setStyleSheet("QComboBox {\n"
"                background-color: rgb(255, 255, 255);\n"
"                border: 2px solid  rgb(0, 31, 63);\n"
"                border-radius: 8px;\n"
"                padding: 5px;\n"
"                font-size: 14pt;\n"
"                color: rgb(50, 50, 50);\n"
"            }\n"
"            QComboBox::drop-down {\n"
"                background-color: rgb(0, 31, 63);\n"
"                border: none;\n"
"                width: 25px;\n"
"            }\n"
"            QComboBox::down-arrow {\n"
"                image: url(:/img/src/image/chevron_down.png); \n"
"                width: 12px;\n"
"                height: 12px;\n"
"            }")
        self.maritual_status_comboBox.setObjectName("maritual_status_comboBox")
        self.maritual_status_comboBox.addItem("")
        self.maritual_status_comboBox.setItemText(0, "")
        self.maritual_status_comboBox.addItem("")
        self.maritual_status_comboBox.addItem("")
        self.phone_number_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.phone_number_lineEdit.setGeometry(QtCore.QRect(120, 120, 241, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phone_number_lineEdit.setFont(font)
        self.phone_number_lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid  rgb(0, 31, 63);\n"
"    border-radius: 8px; \n"
"    padding: 5px; \n"
"    font-size: 10pt;\n"
"}")
        self.phone_number_lineEdit.setMaxLength(100)
        self.phone_number_lineEdit.setObjectName("phone_number_lineEdit")
        self.email_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.email_lineEdit.setGeometry(QtCore.QRect(120, 170, 241, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email_lineEdit.setFont(font)
        self.email_lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid  rgb(0, 31, 63);\n"
"    border-radius: 8px; \n"
"    padding: 5px; \n"
"    font-size: 10pt;\n"
"}")
        self.email_lineEdit.setMaxLength(100)
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.number_of_children_spinBox = QtWidgets.QSpinBox(self.frame)
        self.number_of_children_spinBox.setGeometry(QtCore.QRect(120, 20, 241, 35))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(14)
        self.number_of_children_spinBox.setFont(font)
        self.number_of_children_spinBox.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(0, 31, 63);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-size: 14pt;\n"
"    color: rgb(50, 50, 50);\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    background-color: rgb(0, 31, 63);\n"
"    border-top-right-radius: 8px; \n"
"    image: url(:/img/src/image/chevron_up.png)\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    background-color: rgb(0, 31, 63);\n"
"    border-bottom-right-radius: 8px;\n"
"    image: url(:/img/src/image/chevron_down.png)\n"
"}")
        self.number_of_children_spinBox.setObjectName("number_of_children_spinBox")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(20, 180, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:  rgb(0, 31, 63);")
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(20, 120, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:  rgb(0, 31, 63);")
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(20, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:  rgb(0, 31, 63);")
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:  rgb(0, 31, 63);")
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.update_pushButton = QtWidgets.QPushButton(Dialog)
        self.update_pushButton.setMinimumSize(QtCore.QSize(0, 51))
        self.update_pushButton.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(16)
        self.update_pushButton.setFont(font)
        self.update_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 31, 63);\n"
"border-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(58, 109, 140);\n"
"}")
        self.update_pushButton.setObjectName("updte_pushButton")
        self.gridLayout.addWidget(self.update_pushButton, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Update Personal Information"))
        self.maritual_status_comboBox.setItemText(1, _translate("Dialog", "Single"))
        self.maritual_status_comboBox.setItemText(2, _translate("Dialog", "Married"))
        self.label_11.setText(_translate("Dialog", "EMAIL"))
        self.label_10.setText(_translate("Dialog", "PHONE NUMBER"))
        self.label_12.setText(_translate("Dialog", "MARITUAL STATUS"))
        self.label_13.setText(_translate("Dialog", "NUMBER OF CHILDREN"))
        self.update_pushButton.setText(_translate("Dialog", "UPDATE"))


