# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import design.res
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        Form.setMinimumSize(QtCore.QSize(0, 600))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/src/image/icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(24)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.my_profile_page = QtWidgets.QWidget()
        self.my_profile_page.setObjectName("my_profile_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.my_profile_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.my_profile_page)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setStyleSheet("border: 2px solid;\n"
"border-color:  rgb(0, 31, 63);\n"
"border-radius: 20px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMinimumSize(QtCore.QSize(71, 0))
        self.label_3.setMaximumSize(QtCore.QSize(71, 16777215))
        self.label_3.setStyleSheet("border: 0px solid;\n"
"border-radius: 0px;\n"
"image:url(:/img/src/image/profile.png)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.user_full_name_textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.user_full_name_textEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.user_full_name_textEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.user_full_name_textEdit.setStyleSheet("border: 0px solid;\n"
"border-radius: 0px;\n"
"color: rgb(0, 31, 63);")
        self.user_full_name_textEdit.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.user_full_name_textEdit.setReadOnly(True)
        self.user_full_name_textEdit.setObjectName("user_full_name_textEdit")
        self.gridLayout_4.addWidget(self.user_full_name_textEdit, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 2)
        self.frame_3 = QtWidgets.QFrame(self.my_profile_page)
        self.frame_3.setStyleSheet("background-color: rgb(0, 31, 63);\n"
"border-radius: 20px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMinimumSize(QtCore.QSize(0, 55))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setMinimumSize(QtCore.QSize(367, 0))
        self.label_4.setMaximumSize(QtCore.QSize(367, 16777215))
        self.label_4.setStyleSheet("image: url(:/img/src/image/investment-data-amico.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5.addWidget(self.frame_5, 1, 0, 1, 1)
        self.edit_pushButton = QtWidgets.QPushButton(self.frame_4)
        self.edit_pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.edit_pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.edit_pushButton.setFont(font)
        self.edit_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 31, 63);\n"
"border-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(58, 109, 140);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/src/image/edit_row.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.edit_pushButton.setIcon(icon1)
        self.edit_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.edit_pushButton.setObjectName("edit_pushButton")
        self.gridLayout_5.addWidget(self.edit_pushButton, 3, 1, 1, 1)
        self.worker_info_tableView = QtWidgets.QTableView(self.frame_4)
        self.worker_info_tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.worker_info_tableView.setObjectName("worker_info_tableView")
        self.gridLayout_5.addWidget(self.worker_info_tableView, 1, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 15))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 15))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_5.addWidget(self.frame_7, 0, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(15, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5.addWidget(self.frame_6, 1, 2, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 15))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 15))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_5.addWidget(self.frame_9, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_4, 2, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_3.addWidget(self.frame_8, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 1, 0, 1, 2)
        self.stackedWidget.addWidget(self.my_profile_page)
        self.salary_page = QtWidgets.QWidget()
        self.salary_page.setObjectName("salary_page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.salary_page)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.salary_page)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_10.setStyleSheet("background-color: rgb(0, 31, 63);\n"
"border-radius: 20px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setGeometry(QtCore.QRect(220, 540, 120, 80))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 731, 61))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.frame_10, 1, 0, 1, 1)
        self.tableView_2 = QtWidgets.QTableView(self.salary_page)
        self.tableView_2.setStyleSheet("QHeaderView::section {\n"
"    background-color: rgb(0, 31, 63);\n"
"    color: white;\n"
"    font-size: 14pt;\n"
"    font-weight: bold;\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    padding: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: rgb(230, 230, 230);\n"
"    width: 12px;\n"
"    margin: 0px 3px 0px 3px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(150, 150, 150);\n"
"    min-height: 20px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background: rgb(230, 230, 230);\n"
"    height: 12px;\n"
"    margin: 3px 0px 3px 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(150, 150, 150);\n"
"    min-width: 20px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"}")
        self.tableView_2.setObjectName("tableView_2")
        self.gridLayout_6.addWidget(self.tableView_2, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.salary_page)
        self.leave_history_page = QtWidgets.QWidget()
        self.leave_history_page.setObjectName("leave_history_page")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.leave_history_page)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.leave_history_page)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_11.setStyleSheet("background-color: rgb(0, 31, 63);\n"
"border-radius: 20px;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_6 = QtWidgets.QLabel(self.frame_11)
        self.label_6.setGeometry(QtCore.QRect(10, 9, 741, 81))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.frame_11, 0, 0, 1, 1)
        self.tableView_3 = QtWidgets.QTableView(self.leave_history_page)
        self.tableView_3.setStyleSheet("QHeaderView::section {\n"
"    background-color: rgb(0, 31, 63);\n"
"    color: white;\n"
"    font-size: 14pt;\n"
"    font-weight: bold;\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    padding: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: rgb(230, 230, 230);\n"
"    width: 12px;\n"
"    margin: 0px 3px 0px 3px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(150, 150, 150);\n"
"    min-height: 20px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background: rgb(230, 230, 230);\n"
"    height: 12px;\n"
"    margin: 3px 0px 3px 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(150, 150, 150);\n"
"    min-width: 20px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"}")
        self.tableView_3.setObjectName("tableView_3")
        self.gridLayout_7.addWidget(self.tableView_3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.leave_history_page)
        self.request_leave_page = QtWidgets.QWidget()
        self.request_leave_page.setObjectName("request_leave_page")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.request_leave_page)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_7 = QtWidgets.QLabel(self.request_leave_page)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 31, 63);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.request_leave_page)
        self.frame_13.setStyleSheet("")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.frame_13)
        self.calendarWidget_2.setStyleSheet("QCalendarWidget {\n"
"            background-color: rgb(179, 200, 207);\n"
"            border: 1px solid rgb(200, 200, 200);\n"
"            font-size: 12pt;\n"
"            color: rgb(0, 0, 0);\n"
"            font: 25 16pt \"Caros Light\";\n"
"        }\n"
"        QCalendarWidget QToolButton {\n"
"            color: rgb(0, 31, 63);\n"
"            font-size: 12pt;\n"
"            border: none;\n"
"            margin: 5px;\n"
"            padding: 5px;\n"
"            border-radius: 5px;\n"
"            font: 25 16pt \"Caros Light\";\n"
"        }\n"
"        QCalendarWidget QToolButton:hover {\n"
"            background-color: rgb(58, 109, 140);\n"
"            font: 25 16pt \"Caros Light\";\n"
"        }\n"
"        QCalendarWidget QTableView {\n"
"            background-color: rgb(179, 200, 207);\n"
"            color: black;\n"
"            font: 25 16pt \"Caros Light\";\n"
"        }\n"
"        QCalendarWidget QTableView:selected {\n"
"            background-color: rgb(0, 122, 204);\n"
"            color: white;\n"
"            font: 25 16pt \"Caros Light\";\n"
"        }\n"
"        QCalendarWidget QToolButton#qt_calendar_prevmonth {\n"
"            qproperty-icon: none;\n"
"            image: url(:/img/src/image/Left_Dark.png);\n"
"        }\n"
"        QCalendarWidget QToolButton#qt_calendar_nextmonth {\n"
"            qproperty-icon: none;\n"
"            image: url(:/img/src/image/Right_Dark.png)\n"
"        }")
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.gridLayout_9.addWidget(self.calendarWidget_2, 1, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.frame_13)
        self.textEdit.setStyleSheet("border-color: rgb(0, 31, 63);")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_9.addWidget(self.textEdit, 4, 0, 1, 2)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame_13)
        self.calendarWidget.setStyleSheet("QCalendarWidget {\n"
"            background-color: rgb(179, 200, 207);\n"
"            border: 1px solid rgb(200, 200, 200);\n"
"            font-size: 12pt;\n"
"            color: rgb(0, 0, 0);\n"
"            font: 25 16pt \"Caros Light\";\n"
"        }\n"
"        QCalendarWidget QToolButton {\n"
"            color: rgb(0, 31, 63);\n"
"            font-size: 12pt;\n"
"            border: none;\n"
"            margin: 5px;\n"
"            padding: 5px;\n"
"            border-radius: 5px;\n"
"            font: 25 16pt \"Caros Light\";\n"
"        }\n"
"        QCalendarWidget QToolButton:hover {\n"
"            background-color: rgb(58, 109, 140);\n"
"            font: 25 16pt \"Caros Light\";\n"
"        }\n"
"        QCalendarWidget QTableView {\n"
"            background-color: rgb(179, 200, 207);\n"
"            color: black;\n"
"            font: 25 16pt \"Caros Light\";\n"
"        }\n"
"        QCalendarWidget QTableView:selected {\n"
"            background-color: rgb(0, 122, 204);\n"
"            color: white;\n"
"            font: 25 16pt \"Caros Light\";\n"
"        }\n"
"        QCalendarWidget QToolButton#qt_calendar_prevmonth {\n"
"            qproperty-icon: none;\n"
"            image: url(:/img/src/image/Left_Dark.png);\n"
"        }\n"
"        QCalendarWidget QToolButton#qt_calendar_nextmonth {\n"
"            qproperty-icon: none;\n"
"            image: url(:/img/src/image/Right_Dark.png)\n"
"        }")
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_9.addWidget(self.calendarWidget, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_13)
        self.comboBox.setStyleSheet("QComboBox {\n"
"                background-color: rgb(255, 255, 255);\n"
"                border: 1px solid  rgb(0, 31, 63);\n"
"                border-radius: 2px;\n"
"                padding: 5px;\n"
"                font-size: 14pt;\n"
"                color: rgb(50, 50, 50);\n"
"            }\n"
"            QComboBox::drop-down {\n"
"                background-color: rgb(0, 31, 63);\n"
"                border: none;\n"
"                width: 25px;\n"
"            }\n"
"            QComboBox::down-arrow {\n"
"                image: url(:/img/src/image/chevron_down.png); \n"
"                width: 12px;\n"
"                height: 12px;\n"
"            }")
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_9.addWidget(self.comboBox, 3, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.frame_13)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 31, 63);\n"
"border-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(58, 109, 140);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_9.addWidget(self.pushButton, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 31, 63);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(0, 31, 63);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 31, 63);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 2, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 31, 63);\n"
"border-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(58, 109, 140);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_9.addWidget(self.pushButton_2, 5, 1, 1, 1)
        self.gridLayout_8.addWidget(self.frame_13, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.request_leave_page)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget.setStyleSheet("background-color: rgb(179, 200, 207);\n"
"border-radius: 15px;")
        self.widget.setObjectName("widget")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(40, 30, 121, 121))
        self.frame.setStyleSheet("image: url(:/img/src/image/icon.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 160, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 31, 63);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.salary_pushButton = QtWidgets.QPushButton(self.widget)
        self.salary_pushButton.setGeometry(QtCore.QRect(0, 300, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.salary_pushButton.setFont(font)
        self.salary_pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 0px;\n"
"color: rgb(0, 31, 63);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius: 0px;\n"
"background-color: rgb(58, 109, 140);\n"
"color: rgb(0, 31, 63);\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/src/image/salary_view.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.salary_pushButton.setIcon(icon2)
        self.salary_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.salary_pushButton.setObjectName("salary_pushButton")
        self.leave_history_pushButton = QtWidgets.QPushButton(self.widget)
        self.leave_history_pushButton.setGeometry(QtCore.QRect(0, 370, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.leave_history_pushButton.setFont(font)
        self.leave_history_pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 0px;\n"
"color: rgb(0, 31, 63);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius: 0px;\n"
"background-color: rgb(58, 109, 140);\n"
"color: rgb(0, 31, 63);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/src/image/missing_days.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.leave_history_pushButton.setIcon(icon3)
        self.leave_history_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.leave_history_pushButton.setObjectName("leave_history_pushButton")
        self.my_profile_pushButton = QtWidgets.QPushButton(self.widget)
        self.my_profile_pushButton.setGeometry(QtCore.QRect(0, 230, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.my_profile_pushButton.setFont(font)
        self.my_profile_pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 0px;\n"
"color: rgb(0, 31, 63);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius: 0px;\n"
"background-color: rgb(58, 109, 140);\n"
"color: rgb(0, 31, 63);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/src/image/worker.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.my_profile_pushButton.setIcon(icon4)
        self.my_profile_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.my_profile_pushButton.setObjectName("my_profile_pushButton")
        self.exit_pushButton = QtWidgets.QPushButton(self.widget)
        self.exit_pushButton.setGeometry(QtCore.QRect(0, 520, 201, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_pushButton.sizePolicy().hasHeightForWidth())
        self.exit_pushButton.setSizePolicy(sizePolicy)
        self.exit_pushButton.setMinimumSize(QtCore.QSize(201, 41))
        self.exit_pushButton.setMaximumSize(QtCore.QSize(201, 41))
        self.exit_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/img/src/image/exit.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/img/src/image/exit_hover.png);\n"
"}\n"
"")
        self.exit_pushButton.setText("")
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.request_leave_pushButton = QtWidgets.QPushButton(self.widget)
        self.request_leave_pushButton.setGeometry(QtCore.QRect(0, 440, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.request_leave_pushButton.setFont(font)
        self.request_leave_pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 0px;\n"
"color: rgb(0, 31, 63);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius: 0px;\n"
"background-color: rgb(58, 109, 140);\n"
"color: rgb(0, 31, 63);\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/src/image/sending.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.request_leave_pushButton.setIcon(icon5)
        self.request_leave_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.request_leave_pushButton.setObjectName("request_leave_pushButton")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "StaffBase"))
        self.user_full_name_textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><title>Text Alignment</title><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("Form", "YOUR PERSONAL INFORMATION"))
        self.edit_pushButton.setText(_translate("Form", "EDIT"))
        self.label_5.setText(_translate("Form", "SALARY HISTORY"))
        self.label_6.setText(_translate("Form", "LEAVE HISTORY"))
        self.label_7.setText(_translate("Form", "REQUEST LEAVE"))
        self.pushButton.setText(_translate("Form", "GENERATE"))
        self.label_8.setText(_translate("Form", "START DATE"))
        self.label_9.setText(_translate("Form", "END DATE"))
        self.label_10.setText(_translate("Form", "TYPE OF LEAVE"))
        self.pushButton_2.setText(_translate("Form", "SEND"))
        self.label.setText(_translate("Form", "StaffBase"))
        self.salary_pushButton.setText(_translate("Form", "SALARY"))
        self.leave_history_pushButton.setText(_translate("Form", "LEAVE HISTORY"))
        self.my_profile_pushButton.setText(_translate("Form", "MY PROFILE"))
        self.request_leave_pushButton.setText(_translate("Form", "REQUEST LEAVE"))



