# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_leave_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import design.res
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 301))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/src/image/edit_icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(179, 200, 207);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(0, 31, 63);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.worker_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        self.worker_label.setFont(font)
        self.worker_label.setStyleSheet("color: rgb(0, 31, 63);")
        self.worker_label.setText("")
        self.worker_label.setAlignment(QtCore.Qt.AlignCenter)
        self.worker_label.setObjectName("worker_label")
        self.gridLayout_4.addWidget(self.worker_label, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 31, 63);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.type_leave_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.type_leave_comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.type_leave_comboBox.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(14)
        self.type_leave_comboBox.setFont(font)
        self.type_leave_comboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(0, 31, 63);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-size: 14pt;\n"
"    color: rgb(50, 50, 50);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: rgb(0, 31, 63);\n"
"    border: none;\n"
"    width: 25px;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/img/src/image/chevron_down.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: none; \n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(50, 50, 50);\n"
"    font-size: 14pt;\n"
"}\n"
"")
        self.type_leave_comboBox.setObjectName("type_leave_comboBox")
        self.type_leave_comboBox.addItem("")
        self.type_leave_comboBox.setItemText(0, "")
        self.type_leave_comboBox.addItem("")
        self.type_leave_comboBox.addItem("")
        self.type_leave_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.type_leave_comboBox, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 31, 63);")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(0, 31, 63);")
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 1, 1, 1)
        self.start_date_dateEdit = QtWidgets.QDateEdit(self.frame_3)
        self.start_date_dateEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.start_date_dateEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(14)
        self.start_date_dateEdit.setFont(font)
        self.start_date_dateEdit.setStyleSheet("QDateEdit {\n"
"                background-color: rgb(255, 255, 255);\n"
"                border: 2px solid  rgb(0, 31, 63);\n"
"                border-radius: 8px;\n"
"                padding: 5px;\n"
"                font-size: 14pt;\n"
"                color: rgb(50, 50, 50);\n"
"            }\n"
"QDateEdit::drop-down {\n"
"                background-color: rgb(0, 31, 63);\n"
"                border: none;\n"
"                width: 25px;\n"
"            }\n"
"            QDateEdit::down-arrow {\n"
"                image: url(:/img/src/image/chevron_down.png); \n"
"                width: 12px;\n"
"                height: 12px;\n"
"            }\n"
"            QDateEdit QCalendarWidget {\n"
"                background-color: rgb(240, 240, 240);\n"
"                border: 1px solid rgb(200, 200, 200);\n"
"                font-size: 12pt;\n"
"                color: rgb(0, 0, 0);\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"            QDateEdit QCalendarWidget QToolButton {\n"
"                color: rgb(0, 31, 63);\n"
"                font-size: 12pt;\n"
"                border: none;\n"
"                margin: 5px;\n"
"                padding: 5px;\n"
"                border-radius: 5px;\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"            QDateEdit QCalendarWidget QToolButton:hover {\n"
"                background-color: rgb(58, 109, 140);\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"            QDateEdit QCalendarWidget QTableView {\n"
"                background-color: white;\n"
"                color: black;\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"QDateEdit QCalendarWidget QTableView:selected {\n"
"                background-color: rgb(0, 122, 204);\n"
"                color: white;\n"
"                font: 25 16pt \"Caros Light\";\n"
" }\n"
"QDateEdit QCalendarWidget QToolButton#qt_calendar_prevmonth  {\n"
"    qproperty-icon: none;\n"
"    image: url(:/img/src/image/Left_Dark.png)\n"
"}\n"
"\n"
"QDateEdit QCalendarWidget QToolButton#qt_calendar_nextmonth {\n"
"    qproperty-icon: none;\n"
"    image: url(:/img/src/image/Right_Dark.png)\n"
"}\n"
"")
        self.start_date_dateEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.start_date_dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1945, 9, 14), QtCore.QTime(0, 0, 0)))
        self.start_date_dateEdit.setCalendarPopup(True)
        self.start_date_dateEdit.setObjectName("start_date_dateEdit")
        self.gridLayout_3.addWidget(self.start_date_dateEdit, 1, 0, 1, 1)
        self.end_date_dateEdit = QtWidgets.QDateEdit(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Caros Light")
        font.setPointSize(14)
        self.end_date_dateEdit.setFont(font)
        self.end_date_dateEdit.setStyleSheet("QDateEdit {\n"
"                background-color: rgb(255, 255, 255);\n"
"                border: 2px solid  rgb(0, 31, 63);\n"
"                border-radius: 8px;\n"
"                padding: 5px;\n"
"                font-size: 14pt;\n"
"                color: rgb(50, 50, 50);\n"
"            }\n"
"QDateEdit::drop-down {\n"
"                background-color: rgb(0, 31, 63);\n"
"                border: none;\n"
"                width: 25px;\n"
"            }\n"
"            QDateEdit::down-arrow {\n"
"                image: url(:/img/src/image/chevron_down.png); \n"
"                width: 12px;\n"
"                height: 12px;\n"
"            }\n"
"            QDateEdit QCalendarWidget {\n"
"                background-color: rgb(240, 240, 240);\n"
"                border: 1px solid rgb(200, 200, 200);\n"
"                font-size: 12pt;\n"
"                color: rgb(0, 0, 0);\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"            QDateEdit QCalendarWidget QToolButton {\n"
"                color: rgb(0, 31, 63);\n"
"                font-size: 12pt;\n"
"                border: none;\n"
"                margin: 5px;\n"
"                padding: 5px;\n"
"                border-radius: 5px;\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"            QDateEdit QCalendarWidget QToolButton:hover {\n"
"                background-color: rgb(58, 109, 140);\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"            QDateEdit QCalendarWidget QTableView {\n"
"                background-color: white;\n"
"                color: black;\n"
"                font: 25 16pt \"Caros Light\";\n"
"            }\n"
"QDateEdit QCalendarWidget QTableView:selected {\n"
"                background-color: rgb(0, 122, 204);\n"
"                color: white;\n"
"                font: 25 16pt \"Caros Light\";\n"
" }\n"
"QDateEdit QCalendarWidget QToolButton#qt_calendar_prevmonth  {\n"
"    qproperty-icon: none;\n"
"    image: url(:/img/src/image/Left_Dark.png)\n"
"}\n"
"\n"
"QDateEdit QCalendarWidget QToolButton#qt_calendar_nextmonth {\n"
"    qproperty-icon: none;\n"
"    image: url(:/img/src/image/Right_Dark.png)\n"
"}\n"
"")
        self.end_date_dateEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.end_date_dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1945, 9, 14), QtCore.QTime(0, 0, 0)))
        self.end_date_dateEdit.setCalendarPopup(True)
        self.end_date_dateEdit.setObjectName("end_date_dateEdit")
        self.gridLayout_3.addWidget(self.end_date_dateEdit, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Caros Black")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 31, 63);\n"
"border-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(58, 109, 140);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_4, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit Leave"))
        self.label_9.setText(_translate("Dialog", "WORKER"))
        self.label_10.setText(_translate("Dialog", "TYPE OF LEAVE"))
        self.type_leave_comboBox.setItemText(1, _translate("Dialog", "Sick"))
        self.type_leave_comboBox.setItemText(2, _translate("Dialog", "Vacation"))
        self.type_leave_comboBox.setItemText(3, _translate("Dialog", "Time Off"))
        self.label_11.setText(_translate("Dialog", "START DAY"))
        self.label_12.setText(_translate("Dialog", "END DAY"))
        self.pushButton.setText(_translate("Dialog", "UPDATE"))

